package group.skytale.app.ui

import androidx.compose.runtime.staticCompositionLocalOf
import group.skytale.app.data.AppLanguage

data class SkytaleStrings(
    val appName: String,
    val continueLabel: String,
    val back: String,
    val cancel: String,
    val chooseActionTitle: String,
    val chooseActionSubtitle: String,
    val chooseLanguageTitle: String,
    val chooseLanguageSubtitle: String,
    val createAccount: String,
    val createAccountHint: String,
    val signIn: String,
    val signInHint: String,
    val usernameTitle: String,
    val usernameSubtitle: String,
    val username: String,
    val passwordTitle: String,
    val passwordSubtitle: String,
    val password: String,
    val currentPassword: String,
    val newPassword: String,
    val changePassword: String,
    val nicknameTitle: String,
    val nicknameSubtitle: String,
    val nickname: String,
    val about: String,
    val passwordAdvice: String,
    val generatePassword: String,
    val chats: String,
    val feed: String,
    val settings: String,
    val profile: String,
    val contacts: String,
    val searchChats: String,
    val addContact: String,
    val searchPeople: String,
    val searchPeopleHint: String,
    val noChatsTitle: String,
    val noChatsBody: String,
    val sendMessage: String,
    val messageSearch: String,
    val online: String,
    val lastSeen: String,
    val typing: String,
    val save: String,
    val security: String,
    val logout: String,
    val logoutOthers: String,
    val notifications: String,
    val previews: String,
    val sound: String,
    val instantSync: String,
    val instantSyncHint: String,
    val theme: String,
    val compactMode: String,
    val haptics: String,
    val archivedChats: String,
    val appLock: String,
    val darkTheme: String,
    val language: String,
    val messageCopied: String,
    val liveNow: String,
    val ghostMode: String,
    val ghostModeHint: String,
    val emptyFeedTitle: String,
    val emptyFeedBody: String,
    val attachLater: String,
    val add: String,
    val block: String,
    val unblock: String,
    val removeContact: String,
    val pin: String,
    val unpin: String,
    val archive: String,
    val unarchive: String,
    val mute: String,
    val unmute: String,
    val clearChat: String,
    val markUnread: String,
    val markRead: String,
    val undoLastRead: String,
    val edit: String,
    val delete: String,
    val messageDeleted: String,
    val deleteAccount: String,
    val deleteAccountWarning: String,
    val copy: String,
    val reply: String,
    val openChat: String,
    val openProfile: String,
    val messageSettings: String,
    val appearanceSettings: String,
    val privacySettings: String,
    val accountSettings: String,
    val settingsOverview: String,
    val onlineVisibility: String,
    val usernameDiscoverabilityLabel: String,
    val themeModeLabel: String,
    val themeSystem: String,
    val themeScarletDark: String,
    val themeSoftLight: String,
    val themeMonoDark: String,
    val themeLightClassic: String,
    val themeTelegramDark: String,
    val everyone: String,
    val contactsOnly: String,
    val nobody: String,
    val applyChanges: String,
    val unlockPrompt: String,
    val retry: String,
    val justNow: String,
    val foundMessages: String,
    val noResults: String,
    val imageReady: String,
    val photoAttachment: String,
    val mediaOptions: String,
    val sendWithoutCompression: String,
    val deleteMetadata: String,
    val optimizedUpload: String,
    val optimizedUploadHint: String,
    val originalUploadHint: String,
)

val LocalSkytaleStrings = staticCompositionLocalOf { englishStrings() }

fun stringsFor(language: AppLanguage): SkytaleStrings = when (language) {
    AppLanguage.RU -> russianStrings()
    AppLanguage.EN -> englishStrings()
}

private fun englishStrings() = SkytaleStrings(
    appName = "Skytale",
    continueLabel = "Continue",
    back = "Back",
    cancel = "Cancel",
    chooseActionTitle = "Secure private messaging.",
    chooseActionSubtitle = "Choose how you want to start.",
    chooseLanguageTitle = "Language",
    chooseLanguageSubtitle = "Select the interface language for this device.",
    createAccount = "Create account",
    createAccountHint = "New account on this device.",
    signIn = "Sign in",
    signInHint = "Use an existing account.",
    usernameTitle = "Username",
    usernameSubtitle = "Use 3-32 characters. Spaces and dots are allowed.",
    username = "Username",
    passwordTitle = "Password",
    passwordSubtitle = "Use a strong password for account security.",
    password = "Password",
    currentPassword = "Current password",
    newPassword = "New password",
    changePassword = "Change password",
    nicknameTitle = "Nickname",
    nicknameSubtitle = "Choose the name visible in chats.",
    nickname = "Nickname",
    about = "About",
    passwordAdvice = "Save this password in a secure place or use a password manager.",
    generatePassword = "Generate secure password",
    chats = "Chats",
    feed = "Info",
    settings = "Settings",
    profile = "Profile",
    contacts = "Contacts",
    searchChats = "Search chats",
    addContact = "Add contact",
    searchPeople = "Find by username",
    searchPeopleHint = "",
    noChatsTitle = "No chats yet",
    noChatsBody = "Add a contact to start the first conversation.",
    sendMessage = "Write a message",
    messageSearch = "Search in chat",
    online = "Online",
    lastSeen = "Last seen",
    typing = "typing...",
    save = "Save",
    security = "Security",
    logout = "Log out",
    logoutOthers = "Log out other devices",
    notifications = "Notifications",
    previews = "Previews",
    sound = "Sound",
    instantSync = "Instant background sync",
    instantSyncHint = "Keeps a lightweight background channel for direct delivery. Notifications now start it automatically in the background.",
    theme = "Theme",
    compactMode = "Compact mode",
    haptics = "Haptics",
    archivedChats = "Show archived chats",
    appLock = "App lock",
    darkTheme = "Dark theme",
    language = "Language",
    messageCopied = "Message copied",
    liveNow = "Protected and online",
    ghostMode = "Ghost mode",
    ghostModeHint = "Hide your presence, reads, and username discovery.",
    emptyFeedTitle = "Feed is empty",
    emptyFeedBody = "Service notices and product updates will appear here.",
    attachLater = "Media delivery will be added later. This build is focused on stable text messaging.",
    add = "Add",
    block = "Block",
    unblock = "Unblock",
    removeContact = "Remove contact",
    pin = "Pin",
    unpin = "Unpin",
    archive = "Archive",
    unarchive = "Unarchive",
    mute = "Mute",
    unmute = "Unmute",
    clearChat = "Clear chat",
    markUnread = "Mark unread",
    markRead = "Mark read",
    undoLastRead = "Undo last read",
    edit = "Edit",
    delete = "Delete",
    messageDeleted = "Message deleted",
    deleteAccount = "Delete account",
    deleteAccountWarning = "Your account will be removed from active use on this server. This action cannot be undone.",
    copy = "Copy",
    reply = "Reply",
    openChat = "Open chat",
    openProfile = "Open profile",
    messageSettings = "Messages",
    appearanceSettings = "Appearance",
    privacySettings = "Privacy",
    accountSettings = "Account",
    settingsOverview = "Categories",
    onlineVisibility = "Who can see my online status",
    usernameDiscoverabilityLabel = "Who can find me by username",
    themeModeLabel = "Theme style",
    themeSystem = "System",
    themeScarletDark = "Scarlet dark",
    themeSoftLight = "Soft light",
    themeMonoDark = "Black and white",
    themeLightClassic = "Light classic",
    themeTelegramDark = "Telegram dark",
    everyone = "Everyone",
    contactsOnly = "Contacts only",
    nobody = "Nobody",
    applyChanges = "Apply changes",
    unlockPrompt = "Unlock Skytale",
    retry = "Retry",
    justNow = "just now",
    foundMessages = "Found messages",
    noResults = "Nothing found",
    imageReady = "Image ready",
    photoAttachment = "Photo",
    mediaOptions = "Attachment options",
    sendWithoutCompression = "Send without compression",
    deleteMetadata = "Delete metadata",
    optimizedUpload = "Optimized upload",
    optimizedUploadHint = "Skytale will resize and recompress the image with almost no visible quality loss for faster delivery.",
    originalUploadHint = "The image will keep its original size when possible. Large files may upload slower.",
)

private fun russianStrings() = SkytaleStrings(
    appName = "Skytale",
    continueLabel = "Далее",
    back = "Назад",
    cancel = "Отмена",
    chooseActionTitle = "Безопасный приватный мессенджер.",
    chooseActionSubtitle = "Выберите, как хотите начать.",
    chooseLanguageTitle = "Язык",
    chooseLanguageSubtitle = "Выберите язык интерфейса для этого устройства.",
    createAccount = "Создать аккаунт",
    createAccountHint = "Новый аккаунт на этом устройстве.",
    signIn = "Войти",
    signInHint = "Войти в существующий аккаунт.",
    usernameTitle = "Логин",
    usernameSubtitle = "От 3 до 32 символов. Пробелы и точки разрешены.",
    username = "Логин",
    passwordTitle = "Пароль",
    passwordSubtitle = "Используйте надёжный пароль для защиты аккаунта.",
    password = "Пароль",
    currentPassword = "Текущий пароль",
    newPassword = "Новый пароль",
    changePassword = "Сменить пароль",
    nicknameTitle = "Никнейм",
    nicknameSubtitle = "Это имя будут видеть ваши собеседники.",
    nickname = "Никнейм",
    about = "О себе",
    passwordAdvice = "Сохраните пароль в безопасном месте или используйте менеджер паролей.",
    generatePassword = "Сгенерировать надёжный пароль",
    chats = "Чаты",
    feed = "Инфо",
    settings = "Настройки",
    profile = "Профиль",
    contacts = "Контакты",
    searchChats = "Поиск по чатам",
    addContact = "Добавить контакт",
    searchPeople = "Найти по логину",
    searchPeopleHint = "",
    noChatsTitle = "Чатов пока нет",
    noChatsBody = "Добавьте контакт, чтобы начать первую переписку.",
    sendMessage = "Введите сообщение",
    messageSearch = "Поиск в чате",
    online = "В сети",
    lastSeen = "Был(а) в сети",
    typing = "печатает...",
    save = "Сохранить",
    security = "Безопасность",
    logout = "Выйти",
    logoutOthers = "Выйти с других устройств",
    notifications = "Уведомления",
    previews = "Предпросмотр",
    sound = "Звук",
    instantSync = "Мгновенная фоновая синхронизация",
    instantSyncHint = "Держит лёгкий фоновый канал для прямой доставки сообщений. Теперь уведомления сами запускают его в фоне.",
    theme = "Тема",
    compactMode = "Компактный режим",
    haptics = "Виброотклик",
    archivedChats = "Показывать архив",
    appLock = "Блокировка приложения",
    darkTheme = "Тёмная тема",
    language = "Язык",
    messageCopied = "Сообщение скопировано",
    liveNow = "Защищено и в сети",
    ghostMode = "Режим призрака",
    ghostModeHint = "Скрывает онлайн, прочтение и поиск по логину.",
    emptyFeedTitle = "Лента пуста",
    emptyFeedBody = "Здесь будут появляться сервисные уведомления и обновления.",
    attachLater = "Поддержка медиа появится позже. Сейчас сборка сфокусирована на стабильных текстовых сообщениях.",
    add = "Добавить",
    block = "Заблокировать",
    unblock = "Разблокировать",
    removeContact = "Удалить контакт",
    pin = "Закрепить",
    unpin = "Открепить",
    archive = "Архивировать",
    unarchive = "Вернуть из архива",
    mute = "Выключить звук",
    unmute = "Включить звук",
    clearChat = "Очистить чат",
    markUnread = "Отметить непрочитанным",
    markRead = "Отметить прочитанным",
    undoLastRead = "Отменить последние прочитанные",
    edit = "Изменить",
    delete = "Удалить",
    messageDeleted = "Сообщение удалено",
    deleteAccount = "Удалить аккаунт",
    deleteAccountWarning = "Аккаунт будет выведен из активного использования на этом сервере. Действие необратимо.",
    copy = "Копировать",
    reply = "Ответить",
    openChat = "Открыть чат",
    openProfile = "Открыть профиль",
    messageSettings = "Сообщения",
    appearanceSettings = "Оформление",
    privacySettings = "Приватность",
    accountSettings = "Аккаунт",
    settingsOverview = "Категории",
    onlineVisibility = "Кто видит мой статус в сети",
    usernameDiscoverabilityLabel = "Кто может найти меня по логину",
    themeModeLabel = "Стиль темы",
    themeSystem = "Системная",
    themeScarletDark = "Тёмная Skytale",
    themeSoftLight = "Светлая",
    themeMonoDark = "Чёрно-белая",
    themeLightClassic = "Светлая классика",
    themeTelegramDark = "Telegram тёмная",
    everyone = "Все",
    contactsOnly = "Только контакты",
    nobody = "Никто",
    applyChanges = "Применить",
    unlockPrompt = "Разблокировать Skytale",
    retry = "Повторить",
    justNow = "только что",
    foundMessages = "Найденные сообщения",
    noResults = "Ничего не найдено",
    imageReady = "Изображение готово",
    photoAttachment = "Фото",
    mediaOptions = "Параметры вложения",
    sendWithoutCompression = "Отправить без сжатия",
    deleteMetadata = "Удалить мета-данные",
    optimizedUpload = "Оптимизированная отправка",
    optimizedUploadHint = "Skytale уменьшит размер и аккуратно пережмёт изображение почти без видимой потери качества.",
    originalUploadHint = "Изображение будет отправлено в исходном размере, если это возможно. Большие файлы загружаются дольше.",
)
